### ISSUE TITLE
Incoming call sound stuttering when the screen is on

### ISSUE THREAD

**Issue by karevn** [karevn/android_device_xiaomi_markw#1]
Just for myself.

Experimenting with governor settings to get rid of this thing.

**Comment by karevn** [comment]
Almost there - resolved for me by adding intermediate CPU frequences.

**Comment by karevn** [comment]
Should be fixed at the build from Oct, 20th. Waiting for input.

**Comment by dntds91** [comment]
Don't know this will help or not,
but I installed Viper4Android , then disable the inbuilt AudioFX & CM Audio Service.
It resolved the problem.
