### ISSUE TITLE
Не заряжается при повторном подключении зарядного в розетку

### ISSUE THREAD

**Issue by dronnikovigor** [karevn/android_device_xiaomi_markw#10]
Путь к проблеме:
1. Ставим телефон на зарядку. 
2. Горит индикатор зелёный, на батарейке загорелось Зарядка.
3. Вынимаем блок питания из розетки (из телефона не вынимаем).
4. Вставляем заново. 
5. Горит зеленый индикатор. Зарядка не отображается. Проценты стоят на месте. 
Было как на сборке от 07.10, так и на 21.10. До этого не проверял.

**Comment by karevn** [comment]
Ага, подтверждаю. Похоже, кривой драйвер, придётся разбираться.
