### ISSUE TITLE
Сбрасывается часовой пояс

### ISSUE THREAD

**Issue by satory-ra** [karevn/android_device_xiaomi_markw#18]
При установке часового пояса "Минск (GTM +3:00)" он сбрасывается на "Москва (GTM +3:00)"

**Comment by karevn** [comment]
Точно такая же проблема есть в MIUI и прошивке Nokia. Я думаю, дело в самом андроиде, поэтому откладываем до лучших времён.

**Comment by satory-ra** [comment]
Возможно решение:
https://github.com/LineageOS/android_device_samsung_lt02lte-common/commit/6f059c45e74103f90ddc272546f12f0fb1fdcfad
