### ISSUE TITLE
sometimes tap settings display blank,wait fewer second display completely settings(Wi-Fi,Bluetooth,SIM Cards,Data usage,More...)

### ISSUE THREAD

**Issue by lovekobeme** [karevn/android_device_xiaomi_markw#21]
markw:/ $ logcat
--------- beginning of main
11-06 08:28:38.849 26009 26009 D LBE-Sec : jackpal.androidterm doesn't have adware config
11-06 08:28:38.856 26009 26009 V Term    : onCreate
11-06 08:28:38.903 26009 26009 D Term    : TermService started
11-06 08:28:38.903 26009 26009 I TermService: Activity called onBind()
11-06 08:28:38.920 26009 26027 I Adreno  : QUALCOMM build                   : a9083cf, Iaf618d42e3
11-06 08:28:38.920 26009 26027 I Adreno  : Build Date                       : 03/14/17
11-06 08:28:38.920 26009 26027 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
11-06 08:28:38.920 26009 26027 I Adreno  : Local Branch                     :
11-06 08:28:38.920 26009 26027 I Adreno  : Remote Branch                    :
11-06 08:28:38.920 26009 26027 I Adreno  : Remote Branch                    :
11-06 08:28:38.920 26009 26027 I Adreno  : Reconstruct Branch               :
11-06 08:28:38.923 26009 26009 I Term    : Bound to TermService
11-06 08:28:38.923 26009 26009 I TermService: Activity binding to service
11-06 08:28:38.925 26009 26027 I OpenGLRenderer: Initialized EGL, version 1.411-06 08:28:38.926 26009 26027 D OpenGLRenderer: Swap behavior 1
11-06 08:28:38.963 26009 26009 I libjackpal-androidterm: JNI_OnLoad
11-06 08:28:38.987 26009 26033 I Term    : waiting for: 26028
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@11-06 08:30:26.319 26009 26009 W IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
11-06 08:30:26.319 26009 26009 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-06 08:30:28.057 26009 26009 V Term    : onCreate
11-06 08:30:28.093 26009 26009 I Term    : Bound to TermService
11-06 08:30:28.093 26009 26009 I TermService: Activity binding to service
11-06 08:30:28.117 26009 26014 I art     : Do partial code cache collection, code=30KB, data=28KB
11-06 08:30:28.118 26009 26014 I art     : After code cache collection, code=28KB, data=27KB
11-06 08:30:28.118 26009 26014 I art     : Increasing code cache capacity to 128KB

**Comment by karevn** [comment]
I don't understand a thing in this description.  Steps to reproduce? Screenshots? Expectations and what's wrong?

**Comment by lovekobeme** [comment]
is the same as open app,too slowly open it,and is Blank screen display,seeing contents in th eapp after waiting  fewer seconds 
link——http://tjhdwt.com/test/123.jpg

**Comment by Yardanico** [comment]
Reuploaded image from unsafe @lovekobeme's website:
![image](https://user-images.githubusercontent.com/21169548/32444236-ef1f2cb0-c312-11e7-99fb-d45b1d3cb1e7.png)

**Comment by lovekobeme** [comment]
markw:/ $ logcat
--------- beginning of main
11-14 23:14:34.392 30069 30069 I art     : Starting a blocking GC AddRemoveAppImageSpace
11-14 23:14:34.501 30069 30069 D LBE-Sec : jackpal.androidterm doesn't have adware config
11-14 23:14:34.509 30069 30069 V Term    : onCreate
11-14 23:14:34.617 30069 30069 D Term    : TermService started
11-14 23:14:34.618 30069 30069 I TermService: Activity called onBind()
11-14 23:14:34.633 30069 30087 I Adreno  : QUALCOMM build                   : a9083cf, Iaf618d42e3
11-14 23:14:34.633 30069 30087 I Adreno  : Build Date                       : 03/14/17
11-14 23:14:34.633 30069 30087 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
11-14 23:14:34.633 30069 30087 I Adreno  : Local Branch                     :
11-14 23:14:34.633 30069 30087 I Adreno  : Remote Branch                    :
11-14 23:14:34.633 30069 30087 I Adreno  : Remote Branch                    :
11-14 23:14:34.633 30069 30087 I Adreno  : Reconstruct Branch               :
11-14 23:14:34.644 30069 30087 I OpenGLRenderer: Initialized EGL, version 1.411-14 23:14:34.645 30069 30087 D OpenGLRenderer: Swap behavior 1
11-14 23:14:34.652 30069 30069 I Term    : Bound to TermService
11-14 23:14:34.653 30069 30069 I TermService: Activity binding to service
11-14 23:14:34.703 30069 30069 I libjackpal-androidterm: JNI_OnLoad
11-14 23:14:34.709 30069 30093 I Term    : waiting for: 30088
11-14 23:15:37.279 30069 30069 W IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
11-14 23:15:37.279 30069 30069 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-14 23:15:38.688 30069 30069 I Term    : Bound to TermService
11-14 23:15:38.688 30069 30069 I TermService: Activity binding to service

**Comment by Yardanico** [comment]
@lovekobeme why did you paste the same log again?

**Comment by lovekobeme** [comment]
i know why is happen on me. because i delete some system app. example Email,Exchange2,jelly.... These app  I'm not  useing. but delete these app. system instabilize is due to  these
