### ISSUE TITLE
[E :HDD] Ptt Socket error sending message to the app!!

### ISSUE THREAD

**Issue by satory-ra** [karevn/android_device_xiaomi_markw#22]
Очень вероятным решением этой ошибки в логе dmesg будет добовление недостающего файла ptt_socket_app в vendor с путем в системе system/bin/ptt_socket_app

**Comment by karevn** [comment]
Fixed with 4aaeb0596559090f3f71b5bfe93bd4a31c6623b0 and https://github.com/karevn/android_vendor_xiaomi_markw_RRN/commit/ed2bd2daec0d66f921dd519e5b9e0b80eb368eb1
