### ISSUE TITLE
Плохо работает GPS

### ISSUE THREAD

**Issue by TyroSpy** [karevn/android_device_xiaomi_markw#25]
Очень медленно находит спутники и местоположение. Низкая точность определения и мало используемых спутников(в сравнении с другими прошивками).
[http://ipic.su/img/img7/fs/Screenshot_20171108-001446.1510089637.png](url)

**Comment by satory-ra** [comment]
Ради интереса решил проверить. У меня нет gapps, по этому поиск спутников только по GPS, установил и запустил Навител, т.е. холодный старт, находился в помещении, спутники обнаружило примерно через 5 секунд.

**Comment by TyroSpy** [comment]
Холодный старт это когда сбросить накопленные данные приемника gps. После установки прошивки например нету данных и у меня поиск занял минуты 3..4 до приемлемой точности 30 метров, хотя и это не очень приемлемо, раньше на других прошивках точность была 10..15 метров, по-этому и написал

**Comment by satory-ra** [comment]
Так, у меня и не было этих данных, я только вчера прошивку поставил, а сегодня Навител установил специально для того, что бы проверить как работает.

**Comment by satory-ra** [comment]
Точность в комнате, примерно в метре от окна была +- 14 м.

**Comment by satory-ra** [comment]
Спутников: 14-16.

**Comment by TyroSpy** [comment]
Возможно у меня были плохие условия приема. Значит все в порядке
