### ISSUE TITLE
Проблема диспетчера загрузок в паре с vpn.

### ISSUE THREAD

**Issue by Alex-red12** [karevn/android_device_xiaomi_markw#27]
1)Включаю openvpn клиент с конфигом zaborona vpn.
2)Пытаемся скачать что угодно через встроенный диспетчер загрузок.
Пример: не качает с активным open vpn любые файлы с 4пда, браузера, соц.сети вконтакте.
Проблема собственно в том что скачать ничего не выходит. Проблема точно не в конфиге.

**Comment by karevn** [comment]
Приведите логи из logcat в моменты рядом с произошедшей проблемой. Удостоверьтесь, что оно работает на официальных сборках для других устройств.
