### ISSUE TITLE
Error: returning -512 value

### ISSUE THREAD

**Issue by satory-ra** [karevn/android_device_xiaomi_markw#29]
У нас в логе часто встречается:
Error: returning -512 value
Может быть вот это решение нам пойдёт:
https://github.com/GUYVER91/Nagatobimaru/commit/95f32a2b7858f0a7c117bd198a8063028ea33391
У нас это место:
https://github.com/karevn/android_kernel_xiaomi_msm8953/blob/1885938055f8d3c5e2f77531dbe08420a88863eb/drivers/usb/gadget/function/f_fs.c#L977
Лог между двумя такими ошибками:
[ 205.324100] Error: returning -512 value
[ 205.327342] (elapsed 0.009 seconds) done.
[ 205.327362] Freezing remaining freezable tasks ... (elapsed 0.004 seconds) done.
[ 205.331718] PM: Entering mem sleep
[ 205.331731] Suspending console(s) (use no_console_suspend to debug)
[ 205.345638] gf:gf_suspend_test.
[ 205.361555] PM: suspend of devices complete after 28.425 msecs
[ 205.364983] PM: late suspend of devices complete after 3.412 msecs
[ 205.369163] qpnp_vadc_suspend_noirq: Aborting suspend, adc conversion requested while suspending
[ 205.369188] dpm_run_callback(): qpnp_vadc_suspend_noirq+0x0/0xac returns -16
[ 205.369206] PM: Device qpnp-vadc-14 failed to suspend noirq: error -16
[ 205.369794] PM: noirq resume of devices complete after 0.578 msecs
[ 205.371062] PM: noirq suspend of devices failed
[ 205.371240] last active wakeup source: HVDCPD_WL
[ 205.372634] PM: early resume of devices complete after 1.560 msecs
[ 205.392445] gf:gf_resume_test.
[ 205.442392] PM: resume of devices complete after 69.743 msecs
[ 205.445182] PM: Finishing wakeup.
[ 205.445192] Restarting tasks ... done.
[ 205.453348] PM: suspend exit 2017-11-11 22:17:55.910788282 UTC
[ 205.478246] qpnp_vadc_conv_seq_request: retry error exceeded
[ 205.478287] qpnp_adc_show: VADC read error with -22
[ 205.507932] qpnp_vadc_conv_seq_request: retry error exceeded
[ 205.507969] qpnp_adc_show: VADC read error with -22
[ 205.772935] PM: suspend entry 2017-11-11 22:17:56.230364792 UTC
[ 205.772963] PM: Syncing filesystems ... done.
[ 205.818314] PM: Preparing system for mem sleep
[ 205.819635] Freezing user space processes ... 
[ 205.825953] Error: returning -512 value

**Comment by Yardanico** [comment]
Ну саму ошибку это не уберет, это уберет лишь логгирование этой ошибки)
