### ISSUE TITLE
Cannot playback flac

### ISSUE THREAD

**Issue by Noname98571** [karevn/android_device_xiaomi_markw#30]
LOS 14.1 version as of 10 November, no sound mods of any kind. The issue persists with AudioFX both enabled and disabled. Players used: BlackPlayer and Play Music (installed as a system app), both worked fine on pre-Nosgoth v3 builds.

**Comment by karevn** [comment]
Were you able to play FLAC on the previous version?
Logcat output when working with the player?

**Comment by Noname98571** [comment]
The 20.10.17 build had no such issue, but the 31.10.17 one and (obviously)
the current one are both unable to play .flac files.

The logcat output is in the attachment.

[image: Text file]
alogcat.2017-11-14-09-54-38+0…
<https://drive.google.com/file/d/1_OOELiu5VU-Gxkm-E7Cs2HGoRF43zikT/view?usp=drivesdk>
