### ISSUE TITLE
Настройки световой индикации уведомлений работают некорректным образом

### ISSUE THREAD

**Issue by userneu** [karevn/android_device_xiaomi_markw#31]
Самая свежая сборка. 1. Суть в том, что если в настройках индикации не активирована опция "Собственные значения" то цвет и частота/продолжительность сигнала не поддаются настройке вообще никак, т.е. как не крути опцию "По умолчанию" - её настройки никак на параметры индикатора не влияют. 2. Если же активировать опцию "Собственные значения" и добавить приложения, то всплывает другая проблема - опция "Скорость мигания" вместо заявленных 5 имеет всего 2 ступени - очень медленная на "Очень медленно" и довольно быстрая на всех остальных. Цвет и продолжительность мигания работают вроде нормально. В целом это все мелочи, но решил все равно отписать, вдруг решение очень простое, там подправить пару циферок.

**Comment by userneu** [comment]
И чтобы воспроизвести проблему нужно пробовать на "живом" не прочитанном уведомлении.

**Comment by karevn** [comment]
Я предполагаю, что речь идёт о сборке от 10 ноября.
Текущий HAL не совсем корректно управляет продолжительностью мигания. Хотя оно не совсем совпадает с настройками в GUI, я считаю это приемлемым. Когда-нибудь у кого-нибудь дойдут руки слегка его подчистить. Если хотите - займитесь. Файл `liblight/lights.c`

**Comment by karevn** [comment]
Проблема ещё есть на сборке от 21.11 или я закрываю?

**Comment by userneu** [comment]
Дайте денёк потестировать.

**Comment by userneu** [comment]
Обе проблемы имеют место быть в неизменном виде. Единственная разница - стала работать индикация пропущенных вызовов. Но это к другому багрепорту.

**Comment by karevn** [comment]
OK. Есть возможность слегка подправить, но идеала не будет.
