### ISSUE TITLE
Не работает световая индикация пропущенных звонков и уведомлений Kate mobile

### ISSUE THREAD

**Issue by userneu** [karevn/android_device_xiaomi_markw#32]
Возможно ещё для каких-то приложений не работает. Пока заметил только с этими. Сборка от 14.11
Добавлять проблемные приложения в настройках световой индикации пробовал, но безрезультатно.

**Comment by userneu** [comment]
Вы бы написали что ли чего вам не хватает, прежде чем закрывать. Что ещё я могу написать? Воспроизводится очень просто - включите световую индикацию и пропустите входящий звонок. Я понимаю что нужен максимально подробный багрепорт но конкретно в данном случае куда подробнее?

**Comment by karevn** [comment]
Я не публиковал сборку от 14.11, то есть это походу вообще о чужом билде. Нет чётких шагов воспроизведения. Нет снимка `logcat` (хотя тут явно надо). Нет описания софтовой конфигурации. Я не знаю что такое Kate Mobile, а вы не пояснили и не дали ссылки.

**Comment by userneu** [comment]
Нет, билд ваш, от 10.11. Написал про 14ое, потому что на 4пда вы опубликовали его 14 числа соответственно. Давайте забудем пока про kate mobile. Вот логкат снятый во время входящего пропущенного звонка. Посмотрите пожалуйста. 
[logcat.txt](https://github.com/karevn/android_device_xiaomi_markw/files/1479461/logcat.txt)
