### ISSUE TITLE
Google Play Store and other apps think it is KitKat version (LOS 14.1)

### ISSUE THREAD

**Issue by harvasyuk** [karevn/android_device_xiaomi_markw#33]
I noticed this issue when i tried to install Skype and there was no new version. Play Store installs 7 version of Skype, but the newest is 8. I also can't install apps (from Play Store) which require Android 5+.

![photo_2017-11-16_00-37-21](https://user-images.githubusercontent.com/17803706/32881406-d57b693c-cab9-11e7-8ff3-ade87d330076.jpg)

**Comment by Yardanico** [comment]
This app thiks that this is a Kit Kat because this app wasn't updated for a long time...

**Comment by harvasyuk** [comment]
So, why i can't install this app (https://play.google.com/store/apps/details?id=com.google.android.apps.nexuslauncher&hl=uk) for example? Or the newest version of Skype?

**Comment by Yardanico** [comment]
Because it's available only for Pixel devices?

**Comment by Yardanico** [comment]
http://www.androidpolice.com/2016/10/19/pixel-launcher-lands-play-store-predictably-compatible-pixel-apk-download/

**Comment by Yardanico** [comment]
Google now has two launcher apps in the Play Store, but you probably can't install the new one. The Pixel Launcher is one of the selling points of the Pixel phones, and remains technically exclusive to them. But of course, we have the APK available for download.

**Comment by Yardanico** [comment]
And Skype 8 installs just fine for me (from Play Store of course) :)

**Comment by harvasyuk** [comment]
Is it only my priblem?  Are there any ways to solve this?

![screenshot_20171116-150025](https://user-images.githubusercontent.com/17803706/32892590-6dc299fc-cadf-11e7-8cd4-3f3d88d1b300.png)

**Comment by Yardanico** [comment]
Ah, I think (I may be not right) Google Play looks for device model name, not for Android version.
So - Skype 8 requires Android 7, but Xiaomi Redmi 4 Prime has Android 6 by default, so that's why Skype 7 is installed.

**Comment by harvasyuk** [comment]
I forgot to mention than Skype 8 was avalible on MIUI 8.5.4.0 Global

**Comment by karevn** [comment]
Any constructive input?

**Comment by harvasyuk** [comment]
LOS 14.1-20171110-225407-UNOFFICIAL-markw, Android 7.1.2
No new Skype version in Play Store avalible.

**Comment by karevn** [comment]
It'd damn constructive, yes. :)

Can this problem be reproduced on other custom ROMs?

**Comment by karevn** [comment]
I was able to install Skype 7.46.0.596 from Play Store right now. So, even if the problem exists it is not caused by the build.

**Comment by Yardanico** [comment]
@karevn well @harvasyuk is asking why Skype 8 can't be installed

**Comment by karevn** [comment]
@Yardanico no idea. The version available varies depending on the device, so PlayStore reports something Skype does not like. Anyway, not a priority for me unless someone will provide good actionable input.
