### ISSUE TITLE
Настройка уведомлений: Не показывается список приложений  для кастомной настройки светодиодов

### ISSUE THREAD

**Issue by Granrage** [karevn/android_device_xiaomi_markw#36]
Доброго времени суток,столкнулся с интересной проблемой относительно индикации уведомлений.Дело в том что как в билде за 10.11,так и за 21.11 в меню настроек "индикации уведомлений",пункт "приложения" пустой.Но разница в том,что в билде за 10.11 помимо отсутствия пунктов так же не работал светодиод(по крайней мере для приложений,для остального не успел затестить).А в билде за 21.11 индикация уже работает,но пункты в настройках для приложений до сех пор отсутствуют.
![photo_2017-11-21_16-52-34](https://user-images.githubusercontent.com/33845799/33078791-6aede938-cedc-11e7-8312-be04368e5f51.jpg)

**Comment by karevn** [comment]
Да, у меня тоже не показывается. Попробуйте снять `logcat` через любое приложение и киньте сюда через gist, посмотрим глубже. Но есть большой шанс что это проблема самой lineage os и всё дело кончится статусом wontfix :)

**Comment by Granrage** [comment]
Просто до этого сидел на RR от hrafninn там с этим все было нормально,но там были какие-то заглюки в плане производительности.А на RR qwertyTom стало батарею есть сильно.Недавно перешел на вашу LOS,пока очень нравится,работает быстро,плавно,с батарейкой все гуд,но смутила только эта ситуация,если бы в билде от 10-го ноября светодиод мигал,я бы может и не заметил даже))
Относительно лога,скорее всего уже завтра только,ибо сегодня уже не как не выйдет скорее всего.

**Comment by karevn** [comment]
Другие сборки - это другие сборки, здесь не место для их обсуждения. Жду от вас снятый  `logcat` или откладываю на неопределённое будущее.

**Comment by Granrage** [comment]
Я конечно прошу прощения за возможно глупый вопрос.Но не могли бы Вы скинуть пример снятия logcat?
И судя по всему это не проблема LOS.
![image](https://user-images.githubusercontent.com/33845799/33148850-17f8ec28-cfd6-11e7-997c-e8c1f7827780.png)

**Comment by karevn** [comment]
Спросите Гугл, он знает.

23 нояб. 2017 г. 1:40 пользователь "Granrage" <notifications@github.com>
написал:

**Comment by Granrage** [comment]
Ожидаемо))

**Comment by karevn** [comment]
Всё правильно, это не проблема Lineage OS. Это отключенная у вас опция "Собственные значения" на  LOS.

**Comment by Granrage** [comment]
А,я понял,по поводу опции и так понятно,я её потом уже отключил просто.Я просто не знал что там еще нужно на плюсик в верху жать,не заметил его сразу.
