### ISSUE TITLE
возможность смены диапазонов wi-fi

### ISSUE THREAD

**Issue by Grant2k** [karevn/android_device_xiaomi_markw#38]
Если это возможно, прошу добавить возможность отключения диапазонов wi-fi 
![android-wi-fi-tips-frequency-band-setting_5a-100651784-large](https://user-images.githubusercontent.com/29144739/33091306-63eaa176-ceff-11e7-829d-307cb612c50f.jpg)

**Comment by karevn** [comment]
Эта возможность есть в самой Lineage OS?

**Comment by Grant2k** [comment]
на 13й было, на 14й нет

**Comment by karevn** [comment]
Если эта возможность есть в _официальной_ 14.1 - найдите, пожалуйста, пруф, поразбираюсь. Если нет - закрываю issue, потому что изменения интерфейса стоковой Lineage OS выходят за рамки целей проекта.

**Comment by Grant2k** [comment]
закрывайте...

**Comment by Yardanico** [comment]
P.S: вы сами можете закрывать свои issues
