### ISSUE TITLE
После ота обновления актуальное обновление остаётся в списке для скачивания

### ISSUE THREAD

**Issue by sven4eg** [karevn/android_device_xiaomi_markw#39]
Версия 10.11, 21.11 после обновления на эти версии в списке доступных для скачивания обновлений висят за эти же даты.

**Comment by karevn** [comment]
Скриншот, пожалуйста.

**Comment by Yardanico** [comment]
https://i.imgur.com/KBOGYYS.png

**Comment by karevn** [comment]
Так задумано.
