### ISSUE TITLE
Проблема с светодиодной индикацией уведомлений

### ISSUE THREAD

**Issue by userneu** [karevn/android_device_xiaomi_markw#4]
1. Во время зарядки работает только индикация зарядки. Это баг или фича? Разиэль в своей моки6 считал за баг, поэтому чинил впоследствии чтобы индикация новых сообщений работала и во время зарядки.
2. От некоторых приложений индикация работает через раз - то при очередном уведомлении работает то нет. Закономерность пока не выявил.

**Comment by Razziell** [comment]
1. Поменять местами 3 и 4 тут https://github.com/LineageOS/android_frameworks_base/blob/cm-14.1/services/core/java/com/android/server/lights/LightsManager.java#L23 , но будет баг - при приходе уведомлений для возвращения индикации зарядки нужно перетыкнуть кабель. Более изящного решения для 6 я не искал.

**Comment by karevn** [comment]
Исправлено в текущей версии. Потом будут улучшения - новый драйвер светодиода и HAL.

**Comment by userneu** [comment]
Текущая это от 31 числа сборка или нужно новую ждать? Исправлены обе проблемы? Спасибо.

**Comment by Yardanico** [comment]
@userneu текущая версия - скорее всего имеется ввиду последняя версия на GitHub, так что нужно ждать новую сборку (я могу быть не прав):
![image](https://user-images.githubusercontent.com/21169548/32441480-f54c1012-c308-11e7-95e4-2aa459fdfbc0.png)

**Comment by karevn** [comment]
@Yardanico да,  именно так.
