### ISSUE TITLE
Проблема с индикатором.

### ISSUE THREAD

**Issue by dronnikovigor** [karevn/android_device_xiaomi_markw#40]
Последняя сборка (21.11).
Приходили сообщения в телеграмме. В один прекрасный момент диод начал мигать оранжевым очень часто( ~каждые пол секунды). 
Приход новых сообщений меняет цвет. После прочтения уведомлений, цвет обратно становится оранжевым.
Заряд 39%, прошивка и ядро без модификаций, только pico gapps. Модем 49.
Режим энергосбережения отключен.
После перезагрузки мигать перестал.

**Comment by karevn** [comment]
Частота мигания сейчас точно работает неправильно, в остальном - надо больше инфы. Собирайте logcat рядом с моментами когда светодиод работает неправильно, показывайте конфигурацию уведомлений в программах и самой системе.
