### ISSUE TITLE
Спам в dmesg: Suspending console(s) (use no_console_suspend to debug)

### ISSUE THREAD

**Issue by satory-ra** [karevn/android_device_xiaomi_markw#41]
Вот это периодически встречается по логу:
923.474979] Suspending console(s) (use no_console_suspend to debug)                    
[  923.485019] gf:gf_suspend_test.           
[  923.492627] [11:38:21.387032] [000000171CF3E529] [syste]  wlan: [E :HDD] hdd_is_apps_power_collapse_allowed: do not allow APPS power collapse-pmcState = 1 scanRspPending = 0 inMiddleOfRoaming = 0 
[  923.492642] [11:38:21.387051] [000000171CF3E689] [syste]  wlan: [F :HDD] __hddDevSuspendHdlr: Not able to suspend wlan
[  923.492654] dpm_run_callback(): platform_pm_suspend+0x0/0x7c returns -1                  [  923.492662] PM: Device a000000.qcom,wcnss-wlan failed to suspend: error -1               
[  923.492667] PM: Some devices failed to suspend, or early wake event detected             
[  923.505128] gf:gf_resume_test.          
[  923.551940] PM: resume of devices complete after 59.264 msecs
Я так понял, что такое сообщение есть, когда Wi-Fi включено, но не подключено ни к какой сети.

**Comment by karevn** [comment]
В будущем уточняй что за спам, а то его там всякого дофига :) Будет у нас десяток issue с одинаковым названием :)

**Comment by satory-ra** [comment]
Хорошо))
