### ISSUE TITLE
brightness

### ISSUE THREAD

**Issue by lovekobeme** [karevn/android_device_xiaomi_markw#42]
sometimes brightness is suddenly change to largest brightness,I went to turn down brightness,slide brightness bar to minimum,but brightness also too lighting,I test it in 11.21 version Los

**Comment by lovekobeme** [comment]
CPU frequency doesn't work on 400 Hz.these photos  is about brightness and cpu problem.
link-http://tjhdwt.com/test/index.php?version=11-21

**Comment by lovekobeme** [comment]
attached

**Comment by lovekobeme** [comment]
![brightness](https://user-images.githubusercontent.com/26919967/33354576-7cef4a4c-d4ee-11e7-8229-9053b23be9ba.png)
![version](https://user-images.githubusercontent.com/26919967/33354598-a068e640-d4ee-11e7-987c-1d4f8029242e.png)

**Comment by lovekobeme** [comment]
download 11.30 version now

**Comment by karevn** [comment]
I don't understand a thing here.

**Comment by lovekobeme** [comment]
where?
