### ISSUE TITLE
автояркость

### ISSUE THREAD

**Issue by DmDS** [karevn/android_device_xiaomi_markw#43]
автояркость работает только на повышение. LOS 21.11.17

**Comment by karevn** [comment]
Нет. Она очень медленно сбрасывает яркость.

**Comment by DmDS** [comment]
Нельзя ли сделать побыстрее?  Секунды через 4 чтобы сбрасывало?

**Comment by karevn** [comment]
Нет. Автояркость работает неидеально и когда-нибудь до неё дойдут руки, но сейчас это не приоритетно.
