### ISSUE TITLE
cpu frequence

### ISSUE THREAD

**Issue by lovekobeme** [karevn/android_device_xiaomi_markw#44]
in 11.27 version,cpu is work on 1142Hz busy when i close screen,and brightness also exist problem,i think brightness bar doesn't synchronization with auto brightness,sometimes in lighting enviroment,brightness suddenly to max brightness,but brightness bar also previous position,then i slide the brightness process bar to down,but is void

**Comment by karevn** [comment]
There's no 1142 frequency in this build's freq table. Also, please provide detailed descriptions of the facts when submitting issues. Impressions and guesses don't help the development. Only technical input does.

**Comment by lovekobeme** [comment]
I'm not sure 1142Hz,i remember about 1209 or 1401 Hz,I'm back to 10.31 version now

**Comment by lovekobeme** [comment]
![screenshot_20171129-110338](https://user-images.githubusercontent.com/26919967/33356524-ee30d456-d4f7-11e7-8173-9a6d89fec840.png)
![screenshot_20171129-110349](https://user-images.githubusercontent.com/26919967/33356525-ee6a2300-d4f7-11e7-890e-c2ecc44c80c0.png)

**Comment by lovekobeme** [comment]
![screenshot_20171129112151](https://user-images.githubusercontent.com/26919967/33356555-1879350a-d4f8-11e7-8e8e-6e11290b464c.jpg)

**Comment by lovekobeme** [comment]
![Uploading Screenshot_20171129112244.jpg…

![Uploading Screenshot_20171129112244.jpg…]()

]()
