### ISSUE TITLE
CPU activity history

### ISSUE THREAD

**Issue by lovekobeme** [karevn/android_device_xiaomi_markw#45]
![screenshot_20171129-133014](https://user-images.githubusercontent.com/26919967/33359611-9e63f95e-d50a-11e7-8caf-aaa17c4e23e1.png)
![screenshot_20171130-085504](https://user-images.githubusercontent.com/26919967/33407869-45e0ecac-d5ae-11e7-9de4-56d0466744d7.png)
![screenshot_20171201-142835](https://user-images.githubusercontent.com/26919967/33470599-1f8c4d8e-d6a4-11e7-886c-7a33f016e240.png)
![screenshot_20171129-133021](https://user-images.githubusercontent.com/26919967/33359568-66a448d4-d50a-11e7-8e83-8e4a6831d783.png)
![brightness](https://user-images.githubusercontent.com/26919967/33354576-7cef4a4c-d4ee-11e7-8229-9053b23be9ba.png)
![1](https://user-images.githubusercontent.com/26919967/33354618-b736da3a-d4ee-11e7-9899-421e8b8a921b.png)
![version](https://user-images.githubusercontent.com/26919967/33354598-a068e640-d4ee-11e7-987c-1d4f8029242e.png)
![screenshot_20171129-110338](https://user-images.githubusercontent.com/26919967/33356524-ee30d456-d4f7-11e7-8173-9a6d89fec840.png)
![screenshot_20171129-110349](https://user-images.githubusercontent.com/26919967/33356525-ee6a2300-d4f7-11e7-890e-c2ecc44c80c0.png)
![screenshot_20171201-190147](https://user-images.githubusercontent.com/26919967/33480789-ea8d9088-d6cc-11e7-9dd0-24f54635bf2b.png)
![screenshot_20171201-190200](https://user-images.githubusercontent.com/26919967/33480790-ead72d2e-d6cc-11e7-9c2e-461ad202d618.png)

**Comment by Yardanico** [comment]
And? Is this bad for you?

**Comment by lovekobeme** [comment]
i think maybe 10.30 version is best frequence for Los,in 11.31 erson,i didn't do anything,but cpu frequence always active on 2016Hz,during 4 hours,mostly time are srceen off.

**Comment by karevn** [comment]
Nothing actionable for now. If you have any ideas on how to tune governor, etc for better battery life or performance, etc, please test them and provide final results + measurements proving their advantages.

**Comment by lovekobeme** [comment]
Well, I see.
