### ISSUE TITLE
Notification LED 

### ISSUE THREAD

**Issue by dntds91** [karevn/android_device_xiaomi_markw#46]
Notification LED doesn't work at all now.
in the 2017-11-10 & 2017-11-20 builds it works..

How can i help you?
I attached the logcat
do you want more info i'm happy to help.

20171130 build
Inbuilt Kernel (3.18.31-Nosgoth_V3+)

[LED.txt](https://github.com/karevn/android_device_xiaomi_markw/files/1523598/LED.txt)

**Comment by Yardanico** [comment]
Update Los, it works

**Comment by Stribog1** [comment]
Подтверждаю, как минимум на двух последних версиях индикатор уведомлений не работает вообще. Только на зарядку реагирует.

**Comment by karevn** [comment]
LEDs HAL is work-in-progress, so problems may happen. It would be useful if you provided specific notification configurations and steps to reproduce the log above (with specific taps and settings, and more context).

**Comment by dntds91** [comment]
[2017-12-02-22-31-07.txt](https://github.com/karevn/android_device_xiaomi_markw/files/1523991/2017-12-02-22-31-07.txt)
Here are are the steps
Settings --> Notifications --> Configure Notifications --> Notification light
default notification color --> 00fff, pulse length=long, speed= very slow
missed call notification color --> f9ff00, pulse length=long, speed= very slow
messaging notification color --> 00ff45, pulse length=long, speed= very slow

**Comment by Stribog1** [comment]
у меня полный ресет телефона даже с удалением data, но восстановление из гугль аккаунта настроек от hramin

**Comment by Stribog1** [comment]
Проверил, RR от hramin не причем, фулвайп с новыми настройками по дефолту, световых уведомлений нет, звуком блимкает.

**Comment by dntds91** [comment]
Found the culprit. 
Notification light Brightness level set to min.
see the screenshot.

![screenshot_20171203-095116](https://user-images.githubusercontent.com/33085072/33522323-f2d3419a-d80f-11e7-94c9-c452c7a337ec.png)

i'm pretty sure, i didn't change it.

**Comment by karevn** [comment]
@dntds91 thanks. It's non-standard HAL behaviour + zero brightness for some reason (bug in Lineage settings app or something - I don't want to dig there for now). Setting a low priority for now 
- to be fixed some day.
