### ISSUE TITLE
No way to activate softkey (navigation bar)

### ISSUE THREAD

**Issue by gransort** [karevn/android_device_xiaomi_markw#48]
I tried to activate the soft keys on this firmware, but did not find a way to do it.

The key activation point in other LOS firmware is Settings-->Buttons-->Buttons and layout (as in the picture below)

![otherlineage](https://user-images.githubusercontent.com/34314875/33675992-e816e17e-dacd-11e7-9ed6-f155587dae8f.png)

But there is no such item on this firmware.

![buttonssettings](https://user-images.githubusercontent.com/34314875/33676088-314883f2-dace-11e7-900b-65e3100114dc.png)

Although if you search in the settings it is, but it does not work.

![settingssearch](https://user-images.githubusercontent.com/34314875/33676157-56a8f884-dace-11e7-8880-add7d8f37e14.png)

I tried to write a line "qemu.hw.mainkeys=0" in build.prop, but it did not help either.

**Comment by Yardanico** [comment]
You shouldn't post this issue here, it's related to LineageOS in general, not to this repo

**Comment by gransort** [comment]
Please forgive me, I was wrong.

**Comment by karevn** [comment]
@Yardanico questionable. I did not read the relevant code yet, but have a suspicion it's a question of configuration option. Reopening with low priority.

**Comment by Mcoper** [comment]
@gransort Try this: adb shell settings --cm put global dev_force_show_navbar 1.
need root.

**Comment by gransort** [comment]
@Mcoper Cool man! Нour method worked good! Although this does not solve the problem entirely, I mean that this operation can not be done without a computer, but for me everything is fine.

P.S. Sorry for such a long answer.

**Comment by gransort** [comment]
@karevn I believe that this is still a solution to the problem, although it requires additional manipulation.

**Comment by karevn** [comment]
Taking in account it's a rare need to enable them - I think it's a good enough solution.
