### ISSUE TITLE
Не работает LED индикатор в оповещениях

### ISSUE THREAD

**Issue by Stribog1** [karevn/android_device_xiaomi_markw#50]
После изменения HAL светодиода перестал работать индикатор в оповещениях, яркость проверил, максимальная. Наблюдается видимо на некоторых моделях телефона, так как на форме было несколько жалоб. Версия прошивки от 12.12.17. Может быть поможет информация, что  уведомления на заблокированном экране показываются только если телефон подключен к зарядке. Так же пользовательские настройки позволяют выбрать собственный цвет, но не устанавливают его, цвет всегда остается ffff (может поэтому и не моргает)  
Проверял на полностью вайпнутом телефоне, даже без гапсов, чтоб исключить все.
[logcat.txt](https://github.com/karevn/android_device_xiaomi_markw/files/1559614/logcat.txt)  
прилагаю скриншот яркости, а то некоторые не верят :)  
![screenshot_2017-12-15_172305](https://user-images.githubusercontent.com/9930497/34046148-164c1e10-e1bd-11e7-8c26-72eb589a5d61.jpg)

**Comment by Stribog1** [comment]
ради интереса поставил версию от 10 месяца, светодиод блимкает, уведомления на выключенном экране всплывают. Так что это наверное не HAL виноват, а что-то глобальное.

**Comment by Stribog1** [comment]
поставил ядро от 31.10.2017 светодиод работает нормально.

**Comment by Stribog1** [comment]
[logcat.txt](https://github.com/karevn/android_device_xiaomi_markw/files/1609044/logcat.txt)
лог последий

**Comment by Stribog1** [comment]
[logcat.txt](https://github.com/karevn/android_device_xiaomi_markw/files/1622188/logcat.txt)
логкат от 11.01.2017 с последней прошивки

**Comment by karevn** [comment]
Что-то там ничего полезного. Ещё раз чётко опишите проблему с точки зрения пользователя в новой сборке.

**Comment by Stribog1** [comment]
не работает светодиод уведомлений от слова "совсем" сейчас сижу на сборке LOS  от уважаемого Razziell с его предложенным патчем mido_7.1_libs-OLD.zip  Вариант NEW работал но не блимкал.

**Comment by karevn** [comment]
С таким описанием не могу ничем помочь.
