### ISSUE TITLE
SOX ресемплер + режим выключенного экрана 

### ISSUE THREAD

**Issue by enengm** [karevn/android_device_xiaomi_markw#52]
Условие: говернор с нижней граничной частотой 400, плеер с поддержкой hi-res  с возможностью включить SOX ресемплер(альфа 704 poweramp из шапки 4пда+костыль на hires  ).
Включить музыку, дать телефону выключить экран(самому заблокировать/выключить). 
Результат: искажения звука, хрипы и писки при падении частоты ядер ниже 652.
Ожидание: звучание без искажений на рабочих частотах или удержание нижней частоты 652 ядер, если она минимальная при которой ресемплер корректно обрабатывает.

**Comment by Razziell** [comment]
SoX ресемплер достаточно прожорлив, тем более используется альфа версия PA. К прошивке не имеет вообще никакого отношения.

**Comment by karevn** [comment]
Кхе, ну в общем, это проблема из разряда "у тут понастраивал лишнего, а чо у меня не работает?". Можешь почитать посты в чате на тему звука и частот. Тикет закрываю за отсутствием пользы от него.
