### ISSUE TITLE
Lineage 14.1 2017.12.12

### ISSUE THREAD

**Issue by Region116** [karevn/android_device_xiaomi_markw#53]
При разговоре по блютуз гарнитуре, аппарат зависает и ведёт себя неадекватно !

**Comment by karevn** [comment]
Я очень вам сочувствую! Но так как вы проигнорировали все мои просьбы по форматированию отчётов об ошибках - ничем не могу помочь. Перечитайте пост в теме про прошивки, соберите журналы logcat / dmesg - тогда будет с чем работать.
