### ISSUE TITLE
Отсутствие звука при записи.

### ISSUE THREAD

**Issue by enengm** [karevn/android_device_xiaomi_markw#54]
1)включить Фоновое воспроизведение аудио, браузер(firefox), поверамп.
2)вкдючить запись гуглокамерой , снапкамерой, запись ролика фрнталкой вайбер.
Результат. Запись фонового звука не осуществляется в связи с остановкой воспроизведения.
Было точно сам накладывал фоном. Коль, ты сможешь:) с новым годом!

**Comment by karevn** [comment]
Проверьте ещё раз на январской сборке

**Comment by karevn** [comment]
Не воспроизводится
