### ISSUE TITLE
Auto Brightness not decrease

### ISSUE THREAD

**Issue by andialrizki** [karevn/android_device_xiaomi_markw#55]
for test it i use flashlight from other phone and illuminates the top of the device, and brightness will increase, but when I turn the flashlight off, the brightness stuck in full position, does not automatically reduce, I can stop by doing on-off adaptive brightness or locking device.
sorry my english is bad, i hope u can understand what i write

I use LOS 14.1-20180107_203447 karevn

**Comment by karevn** [comment]
Fixed with dfc181c573d0b7a8e14d425b3d7c2662653e2dae
