### ISSUE TITLE
Звук уведомления при автоматическом включенном режиме "не беспокоить"

### ISSUE THREAD

**Issue by Stribog1** [karevn/android_device_xiaomi_markw#57]
Всю ночь блимкал google hangouts, 1 раз ночью недавно  прошел телеграмм. При выставлении в ручном режиме повторить не удалось. Похоже это иногда наплывами, так как до этого хангоут не беспокоил.
[logcat.txt](https://github.com/karevn/android_device_xiaomi_markw/files/1643084/logcat.txt)

**Comment by karevn** [comment]
Я всё ещё не могу работать с таким отчётом - слишком много лога и мало понимания, что именно происходило и что где пошло не так. Надо так:
1. Вы понимаете, что приложения а и б неправильно показывают уведомления в каких-то ситуациях.
2. Вы пытаетесь воспроизвести эти ситуации у себя в течение обозримого времени (до 5 минут) до тех пор, пока не поймёте какой именно минимум действий надо сделать с момента чистой работы, чтобы дела пошли "не так". Чтобы воспроизвести, придётся просить знакомых и т.д. писать вам, или писать самостоятельно с другого устройства. Ловите лог за это время. Отправляете сюда с точным описанием что в какой момент происходило (типа "в 14:50:15 пришло уведомление в телегу, потом я заблокировал телефон, потом примерно в 14:51:05 пришло уведомление туда-то и тут светодиод погас, хотя не должен был). Я проанализирую и тогда _может быть_ пойму что идёт не так.
3. Вы больше не используете отсутствующее в русском языке слово "блимкать". В нём есть слово "мигать".

**Comment by Stribog1** [comment]
1. ночью я спал, хотя сейчас посмотрю по логам на компе.
2. я не точно выразился, диньг звуком (причем я написал что  именно звук работает), но у хангоута свой звук, если его озвучить то он проговорится как блимк.
3. я сначала связал это с google aps, оттуда ноги же растут мессенжера, но вспомнив что мне писали позавчера ночью и я спал спокойно, решил что бага плавающая.

**Comment by Stribog1** [comment]
к сожалению хангоут не пишет время сообщений, это было примерно в 4 утра мск 18.01
PS. blink абсолютно нормальный термин для программиста, только всегда он проговаривался по русски как блимк  (блымк)  по русски значит "хлопать зеньками" т.е. моргать. Мигает ли светодиод или моргает, согласись несущественно. 
PPS. накоплю статистику дополню issue

**Comment by karevn** [comment]
Я дал методику выше. Открывайте заново когда будет инфа, собранная в соответствии с ней. И не в ваших интересах раздражать меня спорами.

**Comment by Stribog1** [comment]
Закрывать нерешенные вопросы - очень плохой метод. Его бы могли пополнить другие пользователи с похожими проблемами (я разработчик  начиная еще с консольного CVS).
PS Хозяин барин. Мне сугубо все равно ваше мнение обо мне, я хотел бы чтоб прошивка стала лучше.

**Comment by karevn** [comment]
Будет лог по моей методике - будут мои действия, иначе мне не с чем работать. Считаете, что ваш путь лучше - все всегда рады рабочим пулл-реквестам.
