### ISSUE TITLE
Fix phone numbers in status sim card and menu "About Phone"

### ISSUE THREAD

**Issue by AndreyZ1981** [karevn/android_device_xiaomi_markw#59]
Please  fix phone numbers in status sim card and menu "About Phone"
Phone number status "unknown"  in sim card menu and menu  "About Phone"  -> general information
 Lineage OS 14.1 от karevn 
 26.01.2018
![screenshot_20180130-105818](https://user-images.githubusercontent.com/35953803/35557041-9d3715ca-05ac-11e8-8566-5727796e987a.png)
![screenshot_20180130-093301](https://user-images.githubusercontent.com/35953803/35557049-a4e3112a-05ac-11e8-84cd-eb9596cfed63.png)

**Comment by karevn** [comment]
I don't think it's a serious problem by itself. Does it lead to any other kindsof problems?

**Comment by AndreyZ1981** [comment]
I always check the numbers there

**Comment by AndreyZ1981** [comment]
некоторые приложения берут данные оттуда

**Comment by karevn** [comment]
Конкретный пример, пожалуйста. Сейчас мне видится что позаниматься этой штукой стоит, но с низким приоритетом.

**Comment by AndreyZ1981** [comment]
Например приложения операторов не видят номеров симок, и вожу вручную, я номера бывает меняю и не запоминаю их.Плюс вспомнить свой номер и посмотреть легко

**Comment by AndreyZ1981** [comment]
За старнаи
