### ISSUE TITLE
Бесконечная масса ошибок в процессе работы

### ISSUE THREAD

**Issue by Granrage** [karevn/android_device_xiaomi_markw#61]
Заметил(благодаря одного парня с форума), что при работе вылетает масса ошибок.
Интересно на сколько они критичны.
И почему-то при сворачивании шторки уведомлений постоянно появляется предупреждение:
`02-04 21:37:01.192: W/InputMethodManagerService(1569):  Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@14ee939 attribute=null, token = android.os.BinderProxy@d6db36d`
Вот лог:
[log_2018-02-04-21_37_06.txt](https://github.com/karevn/android_device_xiaomi_markw/files/1693237/log_2018-02-04-21_37_06.txt)

**Comment by karevn** [comment]
Это ошибка в Java-коде проекта Lineage OS.  Исправление подобного выходит за рамки целей _этого_ проекта.

**Comment by Granrage** [comment]
Собственно как я и думал.Спасибо за подтверждение.
