### ISSUE TITLE
Фонарик и камера

### ISSUE THREAD

**Issue by Alexx-15** [karevn/android_device_xiaomi_markw#63]
Невозможно включить фонарик при активном приложении Камера (независимо от режима вспышки). На MIUI 8 это работало. Есть возможность разблокировать?

**Comment by karevn** [comment]
Есть. Соберите факты, указывающие что это проблема моей сборки, а не Lineage OS в целом. Пока закрываю.

**Comment by Alexx-15** [comment]
Это Не проблема Вашей сборки, как я понял (пробовал разные на основе этой OS). Может, сделаете патч, если не затруднит? Опция-то полезная при фотографировании во время ремонта оборудования, когда видимость "0"!

**Comment by karevn** [comment]
Нет.
