### ISSUE TITLE
Нет уведомлений от ВКонтакте.

### ISSUE THREAD

**Issue by kotelnikovpv** [karevn/android_device_xiaomi_markw#64]
Нет всплывающих (в строке состояния) уведомлений из приложения Вконтакте. Нет вообще и никогда. Испробовал все варианты настройки уведомлений - нет резульиап

**Comment by karevn** [comment]
Нет технических деталей и фактов, из которых следует что это проблема именно в этом проекте, а не в настройках вконтакта или самой Lineage OS. Выясняйте.

**Comment by kotelnikovpv** [comment]
Т.е. проблема известная?

**Comment by karevn** [comment]
Т.е. вы наплевали на все правила оформления отчётов об ошибке. Поэтому я закрыл задачу.
