### ISSUE TITLE
time zone proposal

### ISSUE THREAD

**Issue by krsnff** [karevn/android_device_xiaomi_markw#65]
Available **2017c**, but now we have **2016j** version (14.1-20180213)
![2018-02-14 16 33 22](https://user-images.githubusercontent.com/36478472/36220417-8ff2d3e2-11cb-11e8-845d-c4c22720f13e.png)

**Comment by Yardanico** [comment]
@krsnff это является проблемой LOS

**Comment by karevn** [comment]
It's Lineage OS's issue. Closing.
