### ISSUE TITLE
Диалог входящего звонка слишком легко сворачивается

### ISSUE THREAD

**Issue by krsnff** [karevn/android_device_xiaomi_markw#67]
Извлекать телефон из кармана при вызове приходится затаив дыхание, чтобы приложение звонилки не свернулось. Диалог вызова на разблокированном экране также слишком легко сворачивается: думаешь, что дотянулся большим пальцем до кнопки "ответить", а по факту сворачиваешь эту панель, что приводит к необходимости выискивать её в "шторке".
Можно ли как-то повысить приоритет звонилки, дабы она была всегда сверху? Хочется пользоваться устройством в первую очередь как телефоном, а не как КПК с необязательной и легко сворачиваемой из-за каждого чиха функцией звонилки.
Спасибо!

**Comment by karevn** [comment]
Менять функциональность Lineage OS - вне целей этого проекта проекта.
