### ISSUE TITLE
Add more volume steps

### ISSUE THREAD

**Issue by dronnikovigor** [karevn/android_device_xiaomi_markw#8]
Add more volume steps for talking over headsets. Minimum value is too loud.

**Comment by dronnikovigor** [comment]
Собственно есть предложение подглядеть в xposed модуль VolumeSteps+ и взять оттуда. 
Сам модуль: [(https://github.com/P1nGu1n/VolumeSteps)]
В нашем случае изменения происходят в фреймворке, конкретнее вот в этой строке: [(https://github.com/LineageOS/android_frameworks_base/blob/90c2139b1200fcdca88a2ec3b1f3e074dfcfa784/services/core/java/com/android/server/audio/AudioService.java#L293)]
Можно значение поменять на 10, например.

**Comment by karevn** [comment]
Это проблема самой LineageOS. Обращайтесь к майнтейнерам или создавайте pull request туда.
